version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./packages/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_AUTH_SERVICE_URL=http://localhost:4000
      - VITE_CHAT_SERVICE_URL=http://localhost:4001
    volumes:
      - ./packages/web/src:/app/packages/web/src
    depends_on:
      - auth-service
      - chat-service
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '10'

  auth-service:
    build:
      context: .
      dockerfile: ./packages/auth-service/Dockerfile
    ports:
      - "${AUTH_SERVICE_PORT:-4000}:${AUTH_SERVICE_PORT:-4000}"
      - "9229:9229"
    environment:
      - MONGO_HOST=${MONGO_HOST:-mongo}
      - MONGO_PORT=${MONGO_PORT:-27017}
      - MONGO_DB_NAME=${MONGO_DB_NAME:-chatti}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT:-4000}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '10'

  chat-service:
    build:
      context: .
      dockerfile: ./packages/chat-service/Dockerfile
    ports:
      - "${CHAT_SERVICE_PORT:-4001}:${CHAT_SERVICE_PORT:-4001}"
      - "9230:9229"
    environment:
      - MONGO_HOST=${MONGO_HOST:-mongo}
      - MONGO_PORT=${MONGO_PORT:-27017}
      - MONGO_DB_NAME=${MONGO_DB_NAME:-chatti}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - CHAT_SERVICE_PORT=${CHAT_SERVICE_PORT:-4001}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongo
      - redis
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '10'

  translation-service:
    build:
      context: .
      dockerfile: ./packages/translation-service/Dockerfile
    ports:
      - "${TRANSLATION_SERVICE_PORT:-4002}:${TRANSLATION_SERVICE_PORT:-4002}"
      - "9231:9229"
    environment:
      - MONGO_HOST=${MONGO_HOST:-mongo}
      - MONGO_PORT=${MONGO_PORT:-27017}
      - MONGO_DB_NAME=${MONGO_DB_NAME:-chatti}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - TRANSLATION_SERVICE_PORT=${TRANSLATION_SERVICE_PORT:-4002}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongo
      - redis
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '10'

  mongo:
    image: mongo:latest
    ports:
      - "${MONGO_PORT:-27017}:27017"
    command: mongod --bind_ip_all
    volumes:
      - chatti_mongodb_data:/data/db
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '10'

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: >
      redis-server 
      --appendonly yes 
      --appendfsync everysec 
      --save 900 1 
      --save 300 10 
      --save 60 10000
    volumes:
      - chatti_redis_data:/data
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '10'

volumes:
  chatti_mongodb_data:
  chatti_redis_data: 