version: '3.8'

services:
  web:
    build:
      context: ./packages/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_AUTH_SERVICE_URL=http://localhost:4000
      - VITE_CHAT_SERVICE_URL=http://localhost:4001
    depends_on:
      - auth-service
      - chat-service
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '10'

  auth-service:
    build:
      context: ./packages/auth-service
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/chatti
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '10'

  chat-service:
    build:
      context: ./packages/chat-service
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    environment:
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/chatti
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongo
      - redis
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '10'

  translation-service:
    build:
      context: ./packages/translation-service
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/chatti
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongo
      - redis
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '10'

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - chatti_mongodb_data:/data/db
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '10'

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: >
      redis-server 
      --appendonly yes 
      --appendfsync everysec 
      --save 900 1 
      --save 300 10 
      --save 60 10000
    volumes:
      - chatti_redis_data:/data
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '10'

volumes:
  chatti_mongodb_data:
  chatti_redis_data: 